### ISSUE TITLE
[tracking issue] 1.0 (previously 0.6) push

### ISSUE THREAD

**Issue by korken89** [rtic-rs/rfcs#35]
- [x] 1. “Move back to symmetric lock API” [PR399][pr399] together with “move/unique resources” [PR371][pr371]
- [x] 2. “Mod instead of const” [PR368][pr368]
- [x] 3. "Multi-core removal" [PR355][pr355]
- [x] 4. "Spawn/schedule from anywhere" [PR 390][pr390]
- [x] 5. Dispatchers as app arguments [PR400][pr400]
- [x] 6. Support "Extern tasks" [PR402][pr402]
- [x] 7. "Multilock support" [PR415][pr415]
- [x] 8. "Reschedule/cancel API"
- [x] 9. "New monotonic" [PR547][pr547]
- [x] 10. Document and implement new MSRV [PR568][pr568]

[pr355]: https://github.com/rtic-rs/cortex-m-rtic/pull/355
[pr368]: https://github.com/rtic-rs/cortex-m-rtic/pull/368
[pr371]: https://github.com/rtic-rs/cortex-m-rtic/pull/371
[pr390]: https://github.com/rtic-rs/cortex-m-rtic/pull/390
[pr399]: https://github.com/rtic-rs/cortex-m-rtic/pull/399
[pr400]: https://github.com/rtic-rs/cortex-m-rtic/pull/400
[pr402]: https://github.com/rtic-rs/cortex-m-rtic/pull/402
[pr415]: https://github.com/rtic-rs/cortex-m-rtic/pull/415
[pr547]: https://github.com/rtic-rs/cortex-m-rtic/pull/547
[pr568]: https://github.com/rtic-rs/cortex-m-rtic/pull/568

**Comment by perlindgren** [comment]
3 in progress.

**Comment by little-arhat** [comment]
so all email filters are broken; code breakage to follow... %)

**Comment by korken89** [comment]
Sorry about that :)
We are updating documentation and communicating currently, so there might be a period of confusion.

**Comment by little-arhat** [comment]
@korken89 no worries, thanks for you work! Was just surprised by all the notifications in my default inbox with non familiar name.

Btw, should `cortex-m-rtic` work now?

I have this in Cargo.toml:
```
[dependencies.cortex-m-rtic]
version = "0.5.3"
git = "https://github.com/rtic-rs/cortex-m-rtic"
rev = "cfd5f4785e9c2ae88e666d1fb94a3488904a87f5"
```

but `cargo update` fails:
```
cargo update
    Updating git repository `https://github.com/rust-embedded/cortex-m`
    Updating crates.io index
    Updating git repository `https://github.com/rtic-rs/cortex-m-rtic`
error: no matching package named `cortex-m-rtic` found
location searched: https://github.com/rtic-rs/cortex-m-rtic?rev=cfd5f4785e9c2ae88e666d1fb94a3488904a87f5
```

**Comment by korken89** [comment]
Hi, you can remove the `git` and `rev`, and it should all work :)

**Comment by AfoHT** [comment]
With https://github.com/rtic-rs/rtic-syntax/pull/30 and https://github.com/rtic-rs/cortex-m-rtic/pull/368 merged number 2 in the list: "Mod instead of const" hopefully can be considered done

**Comment by AfoHT** [comment]
1.0 has been released (ages ago), closing :)
